<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="base" nsURI="http://www.eclipse.epsilon.org/incremental/base/ExecutionTrace/1.0"
    nsPrefix="base_et">
  <eClassifiers xsi:type="ecore:EClass" name="IdElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        changeable="false" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleTrace" abstract="true" eSuperTypes="#//IdElement">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/identity" references="#//ModuleTrace/source"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ruleTraces" upperBound="-1"
        eType="#//RuleTrace" containment="true" eOpposite="#//RuleTrace/module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionContexts" upperBound="-1"
        eType="#//ExecutionContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionContext" eSuperTypes="#//IdElement">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//ExecutionContext/contextVariables"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextVariables" ordered="false"
        upperBound="-1" eType="#//ModelElementVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//RuleTrace" eOpposite="#//RuleTrace/executionContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementVariable">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/identity" references="#//ModelElementVariable/name"/>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//ModelElementVariable/value"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//ModelElementTrace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleElementTrace" abstract="true"
      eSuperTypes="#//IdElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="accesses" ordered="false"
        upperBound="-1" eType="#//Access" resolveProxies="false" eOpposite="#//Access/executionTrace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NestedModuleElementTrace" abstract="true"
      eSuperTypes="#//ModuleElementTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentTrace" lowerBound="1"
        eType="#//RuleTrace" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleTrace" abstract="true" eSuperTypes="#//ModuleElementTrace">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//RuleTrace/executionContext #//RuleTrace/module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="#//ModuleTrace" eOpposite="#//ModuleTrace/ruleTraces"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionContext" lowerBound="1"
        eType="#//ExecutionContext" eOpposite="#//ExecutionContext/rules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Access" abstract="true" eSuperTypes="#//IdElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionTrace" lowerBound="1"
        eType="#//ModuleElementTrace" eOpposite="#//ModuleElementTrace/accesses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementAccess" eSuperTypes="#//Access">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//ElementAccess/element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//ModelElementTrace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllInstancesAccess" eSuperTypes="#//Access">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/identity" references="#//AllInstancesAccess/ofKind"/>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//AllInstancesAccess/type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ofKind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ModelTypeTrace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyAccess" eSuperTypes="#//Access">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//PropertyAccess/property"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="#//PropertyTrace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelTrace" eSuperTypes="#//IdElement">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/identity" references="#//ModelTrace/name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelTypeTrace" eSuperTypes="#//IdElement">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/identity" references="#//ModelTypeTrace/name"/>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//ModelTypeTrace/model"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//ModelTrace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementTrace" eSuperTypes="#//IdElement">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/identity" references="#//ModelElementTrace/uri"/>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//ModelTypeTrace/model"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//ModelTrace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyTrace" eSuperTypes="#//IdElement">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/identity" references="#//PropertyTrace/name"/>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//PropertyTrace/element"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//ModelElementTrace"/>
  </eClassifiers>
</ecore:EPackage>
