<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="base" nsURI="http://www.eclipse.epsilon.org/incremental/base/ExecutionTrace/1.0"
    nsPrefix="base_et">
  <eClassifiers xsi:type="ecore:EClass" name="IdElement" abstract="true" interface="true">
    <eOperations name="getIdProperties">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="keyType" value="String"/>
        <details key="valueType" value="Object"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        changeable="false" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleExecutionTrace" abstract="true"
      eSuperTypes="#//IdElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A ModuleExecutionTrace represents the trace of the execution of a particular Epsilon module&#xA;(e.g. Eol, Etl, etc.) for a given script (identified by the source) and a given set of Models."/>
    </eAnnotations>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/identity" references="#//ModuleExecutionTrace/uri"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The path of the source file executed"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moduleElements" upperBound="-1"
        eType="#//ModuleElementTrace" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The module elements that conform the module.&#xA;Each language shoud specialize this class to represent the structure of its AST."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="models" upperBound="-1"
        eType="#//ModelAccess" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The different models involved in the execution"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accesses" ordered="false"
        unique="false" upperBound="-1" eType="#//Access" containment="true" resolveProxies="false"
        eOpposite="#//Access/module">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The different accesses that where recorded during execution."/>
      </eAnnotations>
      <eAnnotations source="https://eclipse.org/epsilon/incremental/factory"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelAccess" eSuperTypes="#//IdElement">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/identity" references="#//ModelAccess/modelName"/>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//ModelAccess/modelTrace"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelTrace" lowerBound="1"
        eType="#//ModelTrace" changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleElementTrace" abstract="true"
      eSuperTypes="#//IdElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A ModuleElementTrace represents the trace of the execution of a particular&#xA;element of an Epsilon module (e.g. Eol, Etl, etc.). "/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextModuleElementTrace" abstract="true"
      eSuperTypes="#//ModuleElementTrace">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A ModuleElementTrace that defines the context of its child module elements, e.g.&#xA;an operaion, rule, etc. There is one ModuleElementTrace for each module element&#xA;present in a module (e.g. one trace per rule), that is, a ModuleElementTrace &#xA;represents the static component of a module element.&#xA;&#xA;During execution (dynamic component), an ExecutionContext is created for each&#xA;invocation of the module element. This ExecutionContext contains the&#xA;ModelElements that define the context and all of the Accesses that ocurred&#xA;during execution of the module element and its children. "/>
    </eAnnotations>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//ContextModuleElementTrace/executionContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionContext" ordered="false"
        unique="false" upperBound="-1" eType="#//ExecutionContext" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The execution context in which this module was executed. "/>
      </eAnnotations>
      <eAnnotations source="https://eclipse.org/epsilon/incremental/dynamic"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InContextModuleElementTrace" abstract="true"
      eSuperTypes="#//ModuleElementTrace">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A ModuleElementTrace that inherits its context from its parent module element.&#xA;There is one InContextModuleElementTrace for each child module element&#xA;present in a module element (e.g. one trace per guard of a rule), that is, an&#xA;InContextModuleElementTrace represents the static component of a child &#xA;module element.&#xA;&#xA;During execution (dynamic component), the InContextModuleElemetTrace&#xA;populates de Accesss of its parent module element."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextModuleElement" lowerBound="1"
        eType="#//ContextModuleElementTrace" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionContext" eSuperTypes="#//IdElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An ExecutionContext is represented by the set of ModelElementVariables and&#xA;Accesses that occured during execution.&#xA;&#xA;For example, in EVL, the ModelElementVariables would contain the ‘self’ (model&#xA;element of the Context type); in in ETL this would be the input (and output&#xA;variables). "/>
    </eAnnotations>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//ExecutionContext/contextVariables"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextVariables" ordered="false"
        upperBound="-1" eType="#//ModelElementVariable" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The variables that make up the context."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementVariable" eSuperTypes="#//IdElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A ModelElementVariable pairs a variable name to the model element assigned to &#xA;that variable during execution."/>
    </eAnnotations>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/identity" references="#//ModelElementVariable/name"/>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//ModelElementVariable/value"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//ModelElementTrace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Access" abstract="true" eSuperTypes="#//IdElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An Access is the super class of all possible types of accesses that can ocurr&#xA;during execution."/>
    </eAnnotations>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//Access/module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="#//ModuleExecutionTrace" eOpposite="#//ModuleExecutionTrace/accesses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//ModuleElementTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="in" lowerBound="1" eType="#//ExecutionContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementAccess" eSuperTypes="#//Access">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An ElementAccess denotes access to a model element as a whole. This usually&#xA;happens when an element is used for a context."/>
    </eAnnotations>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//ElementAccess/element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//ModelElementTrace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllInstancesAccess" eSuperTypes="#//Access">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An AllInstancesAccess denotes access to all elemens of a given type/kind. This &#xA;is the result of a call to all() (and its derivatives)."/>
    </eAnnotations>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/identity" references="#//AllInstancesAccess/ofKind"/>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//AllInstancesAccess/type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ofKind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ModelTypeTrace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyAccess" eSuperTypes="#//Access">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A PropertyAccess denotes access to property of a model element."/>
    </eAnnotations>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//PropertyAccess/property"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The value of the property when it was accessed."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="#//PropertyTrace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelTrace" eSuperTypes="#//IdElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A ModelTrace contains trace information for the elements and types in the model &#xA;that were accessed during execution."/>
    </eAnnotations>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/identity" references="#//ModelTrace/uri"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The uri of the model."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ModelElementTrace" containment="true" eOpposite="#//ModelElementTrace/modelTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//ModelTypeTrace" containment="true" eOpposite="#//ModelTypeTrace/modelTrace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelTypeTrace" eSuperTypes="#//IdElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A PropertyAccess denotes access to property of a model element."/>
    </eAnnotations>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/identity" references="#//ModelTypeTrace/name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelTrace" eType="#//ModelTrace"
        eOpposite="#//ModelTrace/types"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementTrace" eSuperTypes="#//IdElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A ModelElementTrace represents a model element that was accessed during &#xA;execution. The element represented is identified by its uri."/>
    </eAnnotations>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/identity" references="#//ModelElementTrace/uri"/>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//ModelElementTrace/modelTrace"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//PropertyTrace" containment="true" eOpposite="#//PropertyTrace/elementTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelTrace" eType="#//ModelTrace"
        eOpposite="#//ModelTrace/elements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ModelTypeTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kind" upperBound="-1" eType="#//ModelTypeTrace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyTrace" eSuperTypes="#//IdElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A ModelElementTrace represents a model element that was accessed during &#xA;execution. The element represented is identified by its uri."/>
    </eAnnotations>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/identity" references="#//PropertyTrace/name"/>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equivalency" references="#//PropertyTrace/elementTrace"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementTrace" eType="#//ModelElementTrace"
        eOpposite="#//ModelElementTrace/properties"/>
  </eClassifiers>
</ecore:EPackage>
