<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Foo" nsURI="Foo" nsPrefix="Foo">
  <eClassifiers xsi:type="ecore:EClass" name="Parent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objs" upperBound="-1" eType="#//Obj"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Obj">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="singleAttr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listAttr" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="singleObj" eType="#//Meta"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listObj" upperBound="-1"
        eType="#//Meta" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="singleRef" eType="#//Obj"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listRef" upperBound="-1"
        eType="#//Obj"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Meta">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
