<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eol" nsURI="http://www.eclipse.epsilon.org/incremental/eol/ExecutionTrace"
    nsPrefix="eol_et">
  <eClassifiers xsi:type="ecore:EClass" name="IdElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        changeable="false" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleExecution" abstract="true" eSuperTypes="#//IdElement">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equals" references="#//ModuleExecution/model #//ModuleExecution/module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//ModuleTrace"
        containment="true">
      <eAnnotations source="https://eclipse.org/epsilon/incremental/Graph">
        <details key="edge" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" ordered="false"
        upperBound="-1" eType="#//ModelTrace" containment="true">
      <eAnnotations source="https://eclipse.org/epsilon/incremental/Graph">
        <details key="edge" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executions" ordered="false"
        upperBound="-1" eType="#//ExecutionTrace" containment="true">
      <eAnnotations source="https://eclipse.org/epsilon/incremental/Graph">
        <details key="edge" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleTrace" abstract="true" eSuperTypes="#//IdElement">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/OrientDbIndex" references="#//ModuleTrace/source">
      <details key="type" value="NOTUNIQUE_HASH_INDEX"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionTrace" abstract="true" eSuperTypes="#//IdElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="accesses" lowerBound="1"
        upperBound="-1" eType="#//Access" containment="true" resolveProxies="false"
        eOpposite="#//Access/execution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Access" abstract="true" eSuperTypes="#//IdElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="execution" lowerBound="1"
        eType="#//ExecutionTrace" eOpposite="#//ExecutionTrace/accesses">
      <eAnnotations source="https://eclipse.org/epsilon/incremental/Graph">
        <details key="edge" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllInstancesAccess" eSuperTypes="#//Access">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equals" references="#//AllInstancesAccess/type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ofKind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ModelTypeTrace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyAccess" eSuperTypes="#//Access">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equals" references="#//PropertyAccess/property #//Access/execution"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="#//PropertyTrace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelTrace" eSuperTypes="#//IdElement">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/OrientDbIndex" references="#//ModelTrace/name">
      <details key="type" value="NOTUNIQUE_HASH_INDEX"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ModelElementTrace" containment="true" resolveProxies="false" eOpposite="#//ModelElementTrace/model">
      <eAnnotations source="https://eclipse.org/epsilon/incremental/Graph">
        <details key="edge" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" ordered="false"
        upperBound="-1" eType="#//ModelTypeTrace" containment="true" eOpposite="#//ModelTypeTrace/model">
      <eAnnotations source="https://eclipse.org/epsilon/incremental/Graph">
        <details key="edge" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelTypeTrace" eSuperTypes="#//IdElement">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/OrientDbIndex" references="#//ModelTypeTrace/name">
      <details key="type" value="NOTUNIQUE_HASH_INDEX"/>
    </eAnnotations>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equals" references="#//ModelTypeTrace/model"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//ModelTrace"
        eOpposite="#//ModelTrace/types"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementTrace" eSuperTypes="#//IdElement">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/OrientDbIndex" references="#//ModelElementTrace/uri">
      <details key="type" value="NOTUNIQUE_HASH_INDEX"/>
    </eAnnotations>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equals" references="#//ModelTypeTrace/model"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//ModelTrace"
        eOpposite="#//ModelTrace/elements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//PropertyTrace" containment="true" resolveProxies="false" eOpposite="#//PropertyTrace/element">
      <eAnnotations source="https://eclipse.org/epsilon/incremental/Graph">
        <details key="edge" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyTrace" eSuperTypes="#//IdElement">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/OrientDbIndex" references="#//PropertyTrace/name">
      <details key="type" value="NOTUNIQUE_HASH_INDEX"/>
    </eAnnotations>
    <eAnnotations source="https://eclipse.org/epsilon/incremental/equals" references="#//PropertyTrace/element"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//ModelElementTrace" eOpposite="#//ModelElementTrace/properties"/>
  </eClassifiers>
</ecore:EPackage>
