<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eol" nsURI="http://www.eclipse.epsilon.org/incremental/eol/ExecutionTrace"
    nsPrefix="eol_et">
  <eClassifiers xsi:type="ecore:EClass" name="IdElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        changeable="false" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionTrace" abstract="true" eSuperTypes="#//IdElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" upperBound="-1"
        eType="#//Model" containment="true">
      <eAnnotations source="https://eclipse.org/epsilon/incremental/Graph">
        <details key="edge" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" upperBound="-1"
        eType="#//Module" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" abstract="true" eSuperTypes="#//IdElement">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/OrientDbIndex" references="#//Module/source">
      <details key="type" value="NOTUNIQUE_HASH_INDEX"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moduleElements" upperBound="-1"
        eType="#//ModuleElement" containment="true" eOpposite="#//ModuleElement/module">
      <eAnnotations source="https://eclipse.org/epsilon/incremental/Graph">
        <details key="edge" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleElement" abstract="true" eSuperTypes="#//IdElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="#//Module" eOpposite="#//Module/moduleElements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Execution" abstract="true" eSuperTypes="#//IdElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="accesses" lowerBound="1"
        upperBound="-1" eType="#//Access" containment="true" eOpposite="#//Access/execution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Access" abstract="true" eSuperTypes="#//IdElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="execution" lowerBound="1"
        eType="#//Execution" eOpposite="#//Execution/accesses">
      <eAnnotations source="https://eclipse.org/epsilon/incremental/Graph">
        <details key="edge" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllInstancesAccess" eSuperTypes="#//Access">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ofKind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ModelType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyAccess" eSuperTypes="#//Access">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//IdElement">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/OrientDbIndex" references="#//Property/name">
      <details key="type" value="NOTUNIQUE_HASH_INDEX"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//ModelElement" eOpposite="#//ModelElement/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" eSuperTypes="#//IdElement">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/OrientDbIndex" references="#//ModelElement/uri">
      <details key="type" value="NOTUNIQUE_HASH_INDEX"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnyURI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//Model"
        eOpposite="#//Model/elements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true" eOpposite="#//Property/element">
      <eAnnotations source="https://eclipse.org/epsilon/incremental/Graph">
        <details key="edge" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelType" eSuperTypes="#//IdElement">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/OrientDbIndex" references="#//ModelType/name">
      <details key="type" value="NOTUNIQUE_HASH_INDEX"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//Model"
        eOpposite="#//Model/types"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//IdElement">
    <eAnnotations source="https://eclipse.org/epsilon/incremental/OrientDbIndex" references="#//Model/name">
      <details key="type" value="NOTUNIQUE_HASH_INDEX"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ModelElement" containment="true" eOpposite="#//ModelElement/model">
      <eAnnotations source="https://eclipse.org/epsilon/incremental/Graph">
        <details key="edge" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//ModelType" containment="true" eOpposite="#//ModelType/model">
      <eAnnotations source="https://eclipse.org/epsilon/incremental/Graph">
        <details key="edge" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
