<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="car" nsURI="org.eclipse.epsilon.evl.incremental.car" nsPrefix="car">
  <eClassifiers xsi:type="ecore:EClass" name="Parking">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cars" upperBound="-1" eType="#//Car"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Car">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wheels" upperBound="-1"
        eType="#//Wheel" containment="true" eOpposite="#//Wheel/owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wheel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//Car" eOpposite="#//Car/wheels"/>
  </eClassifiers>
</ecore:EPackage>
